### ISSUE TITLE
If channel is already used analogWrite fails.

### ISSUE THREAD

**Issue by ArminJo** [Dlloydev/ESP32-ESP32S2-AnalogWrite#14]
It would be nice to be able to assign a ledc channel to a pin.
I want to use pin 13 but Channel 0 and 2 are already occupied by another libraries and awGetChannel(13) returns -1.
Is there a workaround / solution?

**Comment by Dlloydev** [comment]
Yes, by design `analogWrite` won't work on any pin that has been previously accessed (to avoid conflicts). However, you could try to free up pin 13 in setup ... first by using `analogWrite(13, -1);` then `analogWrite(13, value);`
