### ISSUE TITLE
Can't compil Example 

### ISSUE THREAD

**Issue by appplay01** [Dlloydev/ESP32-ESP32S2-AnalogWrite#20]
file esp32_pwmWrite.ino

C:\Users\xxxxx\Documents\Arduino\libraries\ESP32_ESP32S2_AnalogWrite\src\pwmWrite.cpp: In member function 'float Pwm::write(uint8_t, int32_t, float, uint8_t, uint32_t)':
C:\Users\xxxxx\Documents\Arduino\libraries\ESP32_ESP32S2_AnalogWrite\src\pwmWrite.cpp:216:7: error: 'ledc_channel_config_t' has no non-static data member named 'flags'
       };
       ^
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by Dlloydev** [comment]
Sorry for the late response.

Try using the latest versions:
* Arduino ESP32 Version 2.0.5
* ESP32-ESP32S2-AnalogWrite 3.0.4
