### ISSUE TITLE
calling analogWrite() frequently causes the pin to spend extra time low

### ISSUE THREAD

**Issue by joshua-8** [Dlloydev/ESP32-ESP32S2-AnalogWrite#3]
@Dlloydev First of all, thank you for making a really cool library. Making analogWrite() supported is a big step towards making programs run on both esp32s and standard Arduino boards more easily!

I was looking at the output of the Fade example with an oscilloscope and noticed the signal wasn't quite what I would expect.
![oscilloscope_fade](https://user-images.githubusercontent.com/59814881/116305512-bb85c980-a758-11eb-82ea-567eb942b837.jpg)
Each time analogWrite was called to change the duty cycle on the pin, it seems the pin goes low for approximately 200 microseconds. This interrupts the otherwise good 5kHz PWM signal and means that even if the signal is set to 100% there will be intervals where the pin is LOW after each time analogWrite is called.
This issue could cause unexpected results in any program where analogWrite is called frequently. 

Is ledcSetup getting called every time analogWrite is? That might be what's causing the issue because when I have used ledcSetup once then only ledcWrite later I don't get the dips.
Would it be possible to check if the channel, resolution, or frequency needs to be changed? If only the duty cycle needs to be changed then I don't think ledcSetup needs to be called.

Please let me know if I can help in any way.
Thanks,
    joshua-8

**Comment by Dlloydev** [comment]
Thank you for the detailed feedback! Yes, I think you may have found the root cause ... I'll run some tests later today then hopefully prepare an update - if not today, then very soon ...
Regards,
D. Lloyd

**Comment by Dlloydev** [comment]
The waveform is now looking good. Only update ledcSetup when necessary. All parameters are now checked if changes are made. With analogWrite running continuously in the loop, a 5kHz PWM signal looked good and consistent.

This is the waveform when the duty cycle is changed 25% to 50% repeatedly ....
![image](https://user-images.githubusercontent.com/63488701/116350398-df302a80-a7bf-11eb-9d59-31f4f24bf9a6.png)
This is the waveform when changing both duty cycle and frequency repeatedly ....
![image](https://user-images.githubusercontent.com/63488701/116350599-2dddc480-a7c0-11eb-9f05-df36b6b3863d.png)

analogWrite is now updated to version 2.0.2.

**Comment by Dlloydev** [comment]
Still some variations to test and another update needed.
Should be ready in 1 or 2 days.

**Comment by Dlloydev** [comment]
Well, I think I've ironed out the last wrinkle ... updated to version 2.0.4

**Comment by Dlloydev** [comment]
I believe this is now resolved, thanks again for the feedback!
Please re-open or start a new issue if there's any problems, suggestions etc.
