### ISSUE TITLE
Return value of analogWriteResolution

### ISSUE THREAD

**Issue by ftjuh** [Dlloydev/ESP32-ESP32S2-AnalogWrite#6]
I found that analogWriteResolution() always returns 0. According to the documentation it should return pow(2, resolution).

https://github.com/Dlloydev/ESP32-ESP32S2-AnalogWrite/blob/6474044198650928d9417d0373725ade0fdbd398/analogWrite.cpp#L244

So I assume the term should be either `1 << (resolution & 0xF); ` or just `1 << resolution;`

Thank you for your efforts
Jan

**Comment by Dlloydev** [comment]
Well that shouldn't be too difficult to fix ... thanks!
