### ISSUE TITLE
changing resolution causes a single very short pulse

### ISSUE THREAD

**Issue by joshua-8** [Dlloydev/ESP32-ESP32S2-AnalogWrite#7]
Hi @Dlloydev,
     I was experimenting with using ledc to control a servo, and I found that using ledcSetup seems to cause a pulse to be output on an attached pin. It's more of an issue for servo control (it causes a twitch) than the use case of analogWrite (it wouldn't affect controlling an led), but I thought I'd let you know about this in case you plan to output servo signals (actually, it would be cool if the library would have a function that makes it easy to output servo signal PWM, but that's off topic now).
Here's the code I used:
```
#include "analogWrite.h"

#define analogPin 33 //pin to analogWrite to
#define triggerPin 26 //pin that triggers oscilloscope when resolution changed

void setup() {
  pinMode(triggerPin,OUTPUT);
  digitalWrite(triggerPin,LOW);
  analogWrite(analogPin, 50);
  delay(1000); //wait a bit to get some pulses at the first resolution
  digitalWrite(triggerPin,HIGH); //trigger oscilloscope
  analogWriteResolution(analogPin, 10); //change resolution
}
void loop(){
  delay(1);
}
```
it produced the following signal:
![extra_pulse](https://user-images.githubusercontent.com/59814881/118605085-ba99f380-b76a-11eb-8f22-6913e7843a64.jpg)

**I found a potential fix for this issue: I was able to change frequency with ledcSetup without getting the pulse by using ledcDetachPin, then calling ledcSetup, and then calling ledcAttachPin.**

Since the pulse only happens once when changing resolution this is really not at all a critical bug to fix, but I thought you might want to know about it.

Thank you for spending so much time making great opensource libraries!

-joshua-8

**Comment by Dlloydev** [comment]
Thank you for the detailed info and and fix!
I've pushed a commit with your fix (tested OK on my ESP32 Dev Module).
